apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inferenceservices
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inferenceservices
subjects:
- kind: ServiceAccount
  name: controller
  namespace: system
- kind: ServiceAccount
  name: handlers
  namespace: system
