apiVersion: batch/v1
kind: Job
metadata:
  name: start
spec:
  template:
    spec:
      serviceAccountName: iter8-handlers
      containers:
      - name: ik-start
        image: iter8/iter8-kfserving:latest
        command: ["handlers/scripts/start.sh"]
        env:
        - name: EXPERIMENT_NAMESPACE
          value: EXPERIMENT_NAMESPACE_VALUE
        - name: EXPERIMENT_NAME
          value: EXPERIMENT_NAME_VALUE
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 300
